require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'

BIN = "*.{so,o}"
CLEAN.include ["ext/#{BIN}", "lib/**/#{BIN}", 'ext/Makefile']
NAME = "ruby-gnomekeyring"
VERSION = "0.1.0"

PKG_FILES = %w(CHANGELOG COPYING README Rakefile) +
      Dir.glob("lib/**/*") + Dir.glob("ext/**/*.{h,c,rb}")

SPEC =
  Gem::Specification.new do |s|
    s.name              = NAME
    s.version           = VERSION
    s.platform          = Gem::Platform::RUBY
    s.has_rdoc          = true
    s.extra_rdoc_files  = ["COPYING"]
    s.summary           = "a binding for the gnome keyring api"
    s.description       = s.summary
    s.author            = "Sean Anastasi"
    s.email             = 'sean.anastasi@gmail.com'
    s.homepage          = 'http://seananastasi.com/projects/ruby-gnomekeyring/'
    s.files             = PKG_FILES
    s.require_paths     = ["lib"]
    s.extensions        = FileList["ext/**/extconf.rb"].to_a
  end

task :default => [:compile]
task :compile => [:gnomekeyring_bind]

task :install do
  sh %{rake package}
  sh %{sudo gem install pkg/#{NAME}-#{VERSION}}
end

task :uninstall => [:clean] do
  sh %{sudo gem uninstall #{NAME}}
end

task :package => [:clean]

Rake::GemPackageTask.new(SPEC) do |p|
    p.need_tar = true
    p.gem_spec = SPEC
end


['gnomekeyring_bind'].each do |extension|
    ext = "ext"
    ext_so = "#{ext}/#{extension}.#{Config::CONFIG['DLEXT']}"
    ext_files = FileList[
        "#{ext}/*.c",
        "#{ext}/*.h",
        "#{ext}/*.rl",
        "#{ext}/extconf.rb",
        "#{ext}/Makefile",
        "lib"
    ]

    desc "Builds just the #{extension} extension"
    task extension.to_sym => [ "#{ext}/Makefile", ext_so ]
    
    file "#{ext}/Makefile" => ["#{ext}/extconf.rb"] do
        Dir.chdir(ext) do ruby "extconf.rb" end
    end
    
    file ext_so => ext_files do
        Dir.chdir(ext) do
          sh(RUBY_PLATFORM =~ /mswin/ ? 'nmake' : 'make')
        end
        cp ext_so, "lib"
    end
end


